### ISSUE TITLE
[Milestone 1] Report Preparation

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#118]
A report needs to be prepared according to the assignment description. It shall contain the following sections:
- [x] Title page and a table of contents
    - Title page shall contain course names, group number and contributors
    - Table of contents shall contain page numbers
- [x] Executive Summary: Summary of project status and any changes that are planned for moving forward  
- [x] #122: List and status of deliverables and evaluation of their status 
- [x] Evaluation of tools and processes that you have used to manage your team project.
- [x] A summary of work done by each team member (in tabular format). Include URIs for relevant issues and Wiki pages.

The the deliverables shall be finalized and added to the document:
- [x]  D1- Project repository: up to date wiki pages (as usual constant gardening), issue tracking.
- [x] D2- Requirements: Software Requirement Specification, Scenarios, and Mockups
- [x] D3- Software design documents in UML: use case, class, and sequence diagrams.
    - [x] #124
    - [x] Finalize Class Diagram
- [x] D4- Project plan & RAM (responsibility assignment matrix) & Communication plan
- [x] D5- Milestone report

Finally all the documents shall be compiled and submitted by @oguzpancuk through Moodle.

**Deadline: 2022-04-15, 20:00**

**Comment by erimerkin** [comment]
I have added list and status of deliverables with their completion date to the report file.

**Comment by canatakan** [comment]
All the deliverables were prepared, diagrams were finalized. All sub-tasks are done. 

The deliverables can be found in our repository, [here](https://github.com/bounswe/bounswe2022group7/blob/master/M1-Group-%3C7%3E-Deliverables.pdf).
