### ISSUE TITLE
[Milestone 1] Finalize Use Case Diagram

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#124]
Use Case Diagram shall be finalized before the deadline.

The work that remains:
- [x] Reorganizing the use cases and simplfiying the diagram: Use cases will be rearrenged to appeal to the eye. Connections will be joined as explained below.
- [x] Reviewing the Requirements and the Use Case Diagram together to make sure they match.
- [x] Coloring of the use cases (#116)

Connections will be joined according to the following example. The intial state is seen below:
![image](https://user-images.githubusercontent.com/57228345/163431388-f683eb73-351f-4401-ba6b-ce932552e389.png)

All the filter related use cases inclue `Order results`. To simplfy the graph, following change will be applied:
![image](https://user-images.githubusercontent.com/57228345/163431544-fbfe97ee-5418-46b6-8dd4-848e0da87ea0.png)

Use cases with a similar structure will be identified and simplified.

Deadline: 15.2.2022
Reviewe: It will be shown to the team during the meeting

**Comment by canatakan** [comment]
Coloring was also completed, and the updated Use Case Diagram can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Use-Case-Diagram). Closing the issue.
