### ISSUE TITLE
Make minor changes in the Milestone 1 Report

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#136]
During the submission, we had some minor issues with our report. As I discussed with the TA, we are allowed to fix these little problems. Here are the updates that we should make:

- [x] Change the name of the file from `M1-Group-<7>-Deliverables.pdf` to `M1-Group-7-Deliverables.pdf`
- [x] Move the file under the directory named `deliverables`
- [x] **Change the ordering within the report:** We arranged the report such that the Milestone 1 Report comes at the end of the deliverables because it was listed at the end in the description. However, we then thought that having the report at the beginning, then the other deliverables following it would be a much better design.
- [x] Update the screenshots of the Sequence Diagrams in the report as they have a low resolution in the report
- [x] Add a title before each deliverable

**Deadline: 18/04/2022, 23:59**
**Reviewer: @CahidArda**

**Comment by CahidArda** [comment]
Titles of the sequence diagrams are standardized and they are compiled to [a pdf](https://github.com/bounswe/bounswe2022group7/files/8507528/Sequence.diagram.1.pdf).


Additionaly, the wiki page related to the [Sequence Diagrams](https://github.com/bounswe/bounswe2022group7/wiki/Sequence-Diagrams) is [updated](https://github.com/bounswe/bounswe2022group7/wiki/Sequence-Diagrams/62fe0745119f177766b71c581f813ec7311e1ffd) with the sequence diagrams with standardized titles.

**Comment by canatakan** [comment]
All these minor fixes are completed and the new file is added. It can be viewed here: [the updated Milestone 1 Report](https://github.com/bounswe/bounswe2022group7/blob/master/deliverables/M1-Group-7-Deliverables.pdf).

The first version of the report can be viewed [in this commit](https://github.com/bounswe/bounswe2022group7/commit/fae572992ef47e4500b5b354176f50e98c5b520a).

**Comment by CahidArda** [comment]
The report looks great after the minor fixes. Thanks for the great work!
