### ISSUE TITLE
[Practice App] Front-end Foundation

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#147]
In [the last meeting](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2311), we decided to start working on the practice app by creating the foundations of the app. In the end, we will have an empty app with an empty front-end, an empty back-end and the database.

Once this empty app is completed, the next step will be to divide the features of the practice-app and implement them. Front-end functionality required by each feature will be handled by the person responsible with the feature.

This issue will cover the tasks related to the foundations of the practice-app front-end. The front-end will be created using HTML and Bootstrap. We shall use the functionalities available in Flask to generate a few pages which will be usefull for the practice-app features.

# Tasks

- [x] Create a branch called `practice-app/front-end-base`. Branch out from [practice-app](https://github.com/bounswe/bounswe2022group7/tree/practice_app) branch.
- [x] Create the initial directory for the HTML templates.
- [x] Complete [base.html](https://github.com/bounswe/bounswe2022group7/blob/practice-app/front-end-base/practice-app/website/templates/base.html) file. This template will be the base HTML which will be extended by all the other functionalities. This page shall contain: 
    - A sidebar which will contain hyperlinks to pages available on the website.
    - A main area where the functionalities will be seen. `base.html` won't show anything in this main area. `base.html` will be extended by other HTML templates and the extending templates will fill this main area.
- [ ] ~`base.html` file shall be styled with Bootstrap.~ *Update: We can not view the templates properly yet. This is because we are not running Flask yet. Styling task will be reassigned when the app can be run.*
- [x] Create example templates showcasing how features will be implemented. *Update: the features to be implemented were discussed and decided in a meeting on 4.5.2022*
- [x] Create a pull request and add two other team members as reviewers.

Deadline: 06/05/2022, 14:00

**Comment by CahidArda** [comment]
[practice-app/front-end-base](https://github.com/bounswe/bounswe2022group7/tree/practice-app/front-end-base) branch is created.

**Comment by CahidArda** [comment]
Some resources related to the front-end:
- [Different features of templates](https://www.digitalocean.com/community/tutorials/how-to-use-templates-in-a-flask-application)
- [Javascript Forms](https://www.javascripttutorial.net/javascript-dom/javascript-form/)

**Comment by CahidArda** [comment]
[base.html](https://github.com/bounswe/bounswe2022group7/blob/7bf6ba91067ea993e878e8f4f1aff1b49c19cbd6/practice-app/website/templates/base.html) is added with the commit above. When it is viewed with Chrome, it looks like this:
![image](https://user-images.githubusercontent.com/57228345/166684297-15392819-6207-4f0d-b6eb-931c17245f72.png)

It is rather empty because [base.html](https://github.com/bounswe/bounswe2022group7/blob/7bf6ba91067ea993e878e8f4f1aff1b49c19cbd6/practice-app/website/templates/base.html) will be extended by other templates. There are two blocks to update when extending:
- `functionality`: Name of the functionality extending [base.html](https://github.com/bounswe/bounswe2022group7/blob/7bf6ba91067ea993e878e8f4f1aff1b49c19cbd6/practice-app/website/templates/base.html)
- `content`: Content of the extending template. For instance, when we implement the feature of viewing an event, HTML elements and the JS scripts will be here.

**Comment by demet47** [comment]
![image](https://user-images.githubusercontent.com/64031659/166950362-0ed5bba5-63bd-4d3b-bbc1-0e8228ad3bc5.png)

There is no posting feature yet. A .cfm file should be written to activate thread posting feature. Also CSS should be added to base.html header to tidy up the appearance.

**Comment by atillaturkmen** [comment]
![Opera Snapshot_2022-05-06_095222_view_art_item html](https://user-images.githubusercontent.com/59166549/167081672-a4da83ba-4a34-43ea-9f6a-29c1e164a537.png)

Created an html to display information about art item. 
Data is hardcoded in a dictionary since API is not finished yet. 
When API is finished, fetch function will be commented out to make a GET request and fill the data dynamically.

**Comment by atillaturkmen** [comment]
![Opera Snapshot_2022-05-06_113013_wikipedia_definition html](https://user-images.githubusercontent.com/59166549/167096213-0436e4af-c1fe-424b-aab1-a4a374d3abf8.png)

Created an html to search for a word in wikipedia API.
Entered word is sent to wikipedia API with a GET request as a query parameter.
Response is shown in the page below the form.

**Comment by CahidArda** [comment]
A pull request was created (#154) to merge the changes into the practice_app branch. Closing this issue.
