### ISSUE TITLE
[Practice App] Database Foundation

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#148]
In [Meeting 11](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2311), we decided to start working on the practice app by creating the foundations of the app. In the end, we will have an empty app with an empty front-end, an empty back-end and the database.

Once this empty app is completed, the next step will be to divide the features of the practice-app and implement them. The person responsible with the feature will have to handle the updates in the database, too .

This issue will cover the tasks related to the foundations of the database structure of the practice-app. We shall use SQLAlchemy for database implementation.

# Tasks

- [x] Create a branch called `practice-app/database-base`. Branch out from [practice-app](https://github.com/bounswe/bounswe2022group7/tree/practice_app) branch.
- [x] Complete the `models.py` file.
This file shall contain the database models for: 
    - Events
    - Users (Admins, Regular Users, and Artists)
    - Art Items
    - Discussion Posts
    - Comments
    - Copyright Reports
- [x] Create `__init.py__` file and add basic calls that will be used during the creation of the database.
- [x] Create a pull request and add two other team members as reviewers.

**Deadline: 06/05/2022, 14:00**

**Comment by canatakan** [comment]
After we had an internal meeting, the division of labor for this task was decided to be as below:

| **Assignee** | **Tasks** | **Deadline** | **Tracking** |
| -------- | ------------ | ---------------- | ---------------- |
| @canatakan | **1.** Create a branch called `practice-app/database-base` and add basic `__init.py__` & `model.py` files. <br/><br/> **2.**  Implement _ArtItem_, _DiscussionPost_, and _Comment_ models. | **1.** 04/05/2022, 23:59 <br/><br/> **2.** 06/05/2022, 14:00|  |
| @azizamankenova  | Implement _Event_, _User_, _Artist_, and _Participant_ models. | 06/05/2022, 14:00 |   |
| @mehmeteminipekdal | Implement _Admin_, and _CopyrightReport_ models. | 06/05/2022, 14:00 |   |

@oguzpancuk was not able to participate in the meeting.

**Comment by canatakan** [comment]
The [practice-app/database-base](https://github.com/bounswe/bounswe2022group7/tree/practice-app/database-base) branch is now created and the basic `__init.py__` and `models.py` files are added as noted in #149.

**Comment by canatakan** [comment]
* We merged the `practice-app/database-base` branch to `practice_app` branch in [Meeting #12](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2312). The relevant pull request can be found [here](https://github.com/bounswe/bounswe2022group7/pull/153).
*  We actively monitored the changes during the meeting and finalized the process of creating the fundamental structure by merging all 3 branches.
* Therefore, the final task described in this issue is now completed.

**Comment by canatakan** [comment]
* Since the fundamental structure is already completed, and the branch is merged, this task is mainly completed.

* For completing the `models.py` file quicker, the task of implementing `Admin` and `CopyrightReport` models is re-assigned. This task can be tracked on #169.

* The progress of the `models.py` file can be observed in the repository, and the models mentioned above shall be implemented by @canatakan, and reviewed by @azizamankenova. 

Hence, closing the issue.
