### ISSUE TITLE
[Practice App] Backend foundation

### ISSUE THREAD

**Issue by guneyizol** [bounswe/bounswe2022group7#152]
In [Meeting 11](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2311), we decided to start working on the practice app by creating the foundations of the app. In the end, we will have an empty app with an empty front-end, an empty back-end and the database.

Once this empty app is completed, the next step will be to divide the features of the practice-app and implement them. The person responsible with the feature will have to handle the updates in the database, too .

This issue will cover the tasks related to the foundations of the backend of the practice-app. We shall use the [Flask](https://flask.palletsprojects.com/en/2.1.x/) framework and its extensions.

# Tasks
- [x] Create a branch called practice-app/backend-base. Branch out from [practice-app/database-base](https://github.com/bounswe/bounswe2022group7/tree/practice-app/database-base) branch.
- [x] Create login endpoint (including tests if time permits)
- [x] Create signup endpoint (including tests if time permits)

**Comment by guneyizol** [comment]
The signup endpoint is created.

This is how it works:
![image](https://user-images.githubusercontent.com/56518500/167164432-8da41be2-dae8-4e71-bb6f-27f6429604d2.png)

![image](https://user-images.githubusercontent.com/56518500/167164538-886da7fe-698b-4671-b2da-13a57964e9ba.png)

**Comment by guneyizol** [comment]
Sign up, login, and logout endpoints are implemented in the [auth.py](https://github.com/bounswe/bounswe2022group7/blob/practice-app/backend-base/practice-app/website/auth.py) file.

Sign up and login accepts POST requests with a json body.
Logout accepts GET request and returns a response message with a json body.
