### ISSUE TITLE
[Practice App] Verification Operations

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#162]
In our [12th meeting](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%2312), we decided features that should be implemented. Every member should implement one of the decided features and I chose handling verification-related features like requesting verification, viewing verification requests etc.

The requirements are:

- users shall be able to request verification
- users shall be able to view verification requests
- users shall be able to accept/reject a verification request

I will make necessary updates on models.py and __init__.py. Other than those, a file named verification.py and html files according to the verification.py file will be created.

### To-do List for Features

- [x] create a new branch so that updates won't affect other members' works.
- [x] create a data model for verification request.
- [x] create an endpoint for users to send verification requests.
- [x] create an endpoint for users to view verification requests.
- [x] create an endpoint for users to accept/reject a verification request.
- [x] create the template files.
- [x] connect the frontend templates created.
- [x] assign the reviewer to review the work. (Reviewe: @mehmeteminipekdal )

### To-do List for Testing

- [x] create unit test
- [x] test api endpoints via Postman

**Comment by musasimsekdotdll** [comment]
Hi @CahidArda,

It is a typo. In the third case, if the request is rejected, the status becomes -1. I will update the file as soon as possible.

If a brief explanation needed, I have put that attribute in order to keep track of all verification requests sent by a specific user. While implementing endpoints, I will try to consider all possible cases accordingly .

**Comment by musasimsekdotdll** [comment]
The data model for the verification requests is created with the name "VerificationRequest" in the [models.py](https://github.com/bounswe/bounswe2022group7/blob/practice-app/feature/verification/practice-app/website/models.py).

**Comment by musasimsekdotdll** [comment]
The [result](https://github.com/bounswe/bounswe2022group7/wiki/Practice-App---Postman-Results) of testing API can be found in Wiki.

**Comment by musasimsekdotdll** [comment]
@mehmeteminipekdal, could you review things done and give a feedback?

**Comment by canatakan** [comment]
* The task was reviewed during the final meeting. 

* After the final merge at #235, this feature was successfully integrated to the application.

Thank you for your hard work. Since the task is now completed, the issue can be closed.
