### ISSUE TITLE
[Milestone 2]Create usecase, class and sequence diagrams for participants feature.

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#217]
Design diagrams for participants feature needs to be created. I will create the diagrams for the given requirements:

> 
> 1.1.3.4. Users shall be able to view participants for an event
> 1.1.3.5. Users shall be able to participate in events
> 1.1.3.6. Users shall be able to cancel their participation to an event
> 1.1.3.7. Users shall be able to create a personalized share link to event
> 
> 1.2.3.1. System shall be able to create personalized share links for an event.
> 1.2.3.2. Systems shall limit the participation cancellation to participating user or event's creator.
> 1.2.3.3. System shall limit the viewing participation to logged in users.
> 1.2.3.4. System shall block participation of not logged in and already participating users.

## Tasks:

- [x] Create use case diagram
- [x] Create the class diagram
- [x] Create sequence diagrams

**Deadline: 2022-05-19, 22:00**

**Comment by erimerkin** [comment]
Added these nodes to use case diagram:
<img width="493" alt="resim" src="https://user-images.githubusercontent.com/26660856/169354916-022e0fa9-61f1-440a-8986-c44ea416c508.png">

**Comment by erimerkin** [comment]
Added participant features to Event class diagram:

<img width="246" alt="resim" src="https://user-images.githubusercontent.com/26660856/169355172-4e7e95b8-d2ac-406f-ba9d-77da2f435d4c.png">

**Comment by erimerkin** [comment]
Created sequence diagrams:

### View Participants
![View Participants](https://user-images.githubusercontent.com/26660856/169358617-1743f124-e3b2-4f34-8f6f-b14b9d1273c6.png)

### Add Participant
![Add Participant](https://user-images.githubusercontent.com/26660856/169358852-c79feab1-a7b8-4c0f-918a-fd02e19c23d0.png)


### Remove Participant

![Remove Participants](https://user-images.githubusercontent.com/26660856/169358865-192aef00-c6f6-48e7-b218-6a9859f30024.png)

**Comment by erimerkin** [comment]
### Get Share Link
![Sequence diagram(Practice App) - Get Share Link](https://user-images.githubusercontent.com/26660856/169359818-1bf677a5-a17c-46f6-b1d8-3bd85cebda95.png)

This diagrams will be reviewed in today's meeting.

**Comment by CahidArda** [comment]
The diagrams look great, thanks for the work!
