### ISSUE TITLE
Setting up AWS Deployment 

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#282]
With Milestone 1's date approaching (01.11.2022), we need to deploy our application and connect the components to each other. I am responsible with overseeing the creation of automation (Github Action) workflows that test, build and deploy the applications with a Docker container to AWS. Existing dockerized components should also be reviewed to make them production ready.

Following should be reviewed, built and deployed to AWS before Milestone 1 date:
- Backend (Spring Boot Application)
- Frontend (React)
- Database (MySQL)

### So, the first steps for this task will need setup work on various parts of repository:

- [x] AWS setup 
- [x] Github Actions setup for deployment (AWS keys, environment variables etc.)
- [x] #276: Backend dockerization and CI/CD setup. Ensuring the database and backend connection can be configured on the Github Actions.
- [x] #283

After these steps are completed, deployment to AWS will be done either manually or automatically with Github Actions. Setup and connection should be ensured with a secure manner, like the implementation in previous semester.

- [x] Deployed to AWS

### Tasks after deployment:

- [x] Connecting the containers to each other ( Frontend/Mobile -> Backend -> Database )
- [x] Testing the application

_Additional things that can be done (should be discussed within team):_
- _Setting up a domain name and SSL certificate for our application (HTTPS). This way api could also be accessed via "api.example.com" URL._
- _Seperating the different components from each other ex. a frontend deployment not needing backend redeployment._

**Deadline: 31.10.2022. 23.59**
**Reviewer: @CahidArda **

**Comment by erimerkin** [comment]
I have finished dockerization of frontend and succesfully setup production images. Now I will work and try to help on backend's dockerization and CI/CD steps. 

For AWS part I need to create the infastructure schematic and test the feasibility so I have a clear idea on how to proceed. My initial idea is using ECS with 3 containers running on the same EC2 instance. These containers are: NGINX serving frontend and reverse proxy to API, Backend container, Database container. I will need to check the feasibility of this, if it fails fallback option would be manually running docker images in same EC2 instance.

**Comment by erimerkin** [comment]
I have also suggested changes on backend dockerization on my review https://github.com/bounswe/bounswe2022group7/pull/276#pullrequestreview-1154250162. To continue on that direction, I will wait until the suggested changes are implemented.

**Comment by erimerkin** [comment]
I have setup the AWS ECS, ECR, S3 and RDS services. In AWS RDS a MySQL 8 Database is setup, while this DB is only accessible within same private network(our EC2 instance). Our environment variables for production is stored in S3 as a .env file. 

Now I will initialize the `frontend` branch with necessary files(aws-task-definition and changed nginx.conf) and will check what is needed for configuration on GitHub.

**Comment by erimerkin** [comment]
Deployment of frontend to AWS was successful. [Relevant Action](https://github.com/bounswe/bounswe2022group7/actions/runs/3322058729)

I will now work on backend dockerization and deployment setup with applying my suggested changes in #276.

**Comment by erimerkin** [comment]
I have finished setting up production and development docker images for backend branch in #276. After merging the PR #276, I will start working on CI/CD setup for backend. The detailed description can be accessed from this comment: https://github.com/bounswe/bounswe2022group7/pull/276#issuecomment-1295310673

**Comment by erimerkin** [comment]
The setup for Github Actions (AWS Keys, environment variables) are completed, since all necessary keys were added to repository in previous semester.

**Comment by erimerkin** [comment]
The application is now deployed at http://3.121.123.234/. API can be accessed at http://3.121.123.234/api/ path. 

Necessary actions showing the status of deployment: [backend deployment](https://github.com/bounswe/bounswe2022group7/actions/runs/3361830320) & [frontend deployment](https://github.com/bounswe/bounswe2022group7/actions/workflows/Frontend-AWS-Deployment.yml)

So the final architecture is:
- RDS for hosting the MySQL database
- An NGINX container for serving frontend files and creating a reverse proxy for api at path `/api`
- An spring boot container for backend server

To deploy these containers various technologies are used. AWS' ECR is used to store created backend and frontend images, then AWS ECS deploys these images to containers while getting environment variables from AWS S3. This workflow is triggered by Github Actions as a **release** is created.

![resim](https://user-images.githubusercontent.com/26660856/199034818-e1b2735f-9578-41a2-add2-33b50aaab6a3.png)

**Comment by erimerkin** [comment]
I have created 2 pull requests (#354 and #355) as the implementation step is done for deployment. In case there may be errors or bugs happening after some changes, this issue will be used to make sure the deployed application is fully tested.

As a consistency addition api's context path is updated, not it starts with `/api`. To make sure this doesn't break anything in frontend dev and production testing will be done.

**Comment by erimerkin** [comment]
The PRs #354 and #355 are merged succesfully. Also backend and frontend branches are currently updated and running in AWS. After my and @CahidArda's testing, we have found that the application works as expected. 

So the steps in this issue is compled succesfully. @CahidArda issue is now ready for your review.

**Comment by CahidArda** [comment]
The app was succesfully deployed and is accessible. Thanks for the superb work.

Closing the issue.
