### ISSUE TITLE
Preparing Deliverables for Milestone

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#329]
We are required to put our deliverables in a folder for the first CMPE451 milestone. Here is the related section from the milestone description:

> In addition to the code that you develop you must create a folder titled CMPE451_Customer_Presentation_Milestone_1 inside deliverables folder in your repository. Commit all the deliverables to this directory (with appropriate comments)

### List of Deliverables

The deliverables will include the following:
- Software Requirements Specification
- Software Design (UML)
- Scenarios and Mockups
- Project Plan
- Individual Contribution Reports

These deliverables are ready except for sequence diagrams, project plan and individual contribution reports. Here is how we can handle the deliverables:
- [x] @canatakan adds use case and class diagrams.
- [x] @CahidArda adds rest of the deliverables excluding sequence diagrams, project plan and individual contribution reports.
- [x] We add sequence diagrams and project plan on monday 19:00
- [x] @CahidArda creates individual contribution report template. Template will include the names of the team members in alphabetic order.

I suggest we create a branch out of develop and add the files there, then merge it back into develop branch. There will be a lot of commits from many people for the individual contribution report. We can keep these changes in a seperate branch until most people finish their individual report.

Deadline 31.10.2022, 23:59
Reviewer: @demet47

**Comment by canatakan** [comment]
* I agree with your suggestion about creating a branch out of `develop` and adding the files there. 
* I am also going to update this page whenever I make contributions.
* The conclusions that have been decided during our meetings about the Sequence Diagrams or the Project Plan, etc. can be added here for reference as well.

**Comment by demet47** [comment]
Can you tag the branch when you create one? 
![image](https://user-images.githubusercontent.com/64031659/198891115-35810c0a-d81f-49e0-bdbe-372313e1a252.png)
It can be done by clicking develop here and it gives a list of accessable branches. You can select the related branch when you create one.

**Comment by canatakan** [comment]
I added `dev/deliverables` branch to the `Development` of this issue.

**Comment by canatakan** [comment]
* As can be seen in the commit b349b699fc5a30dd1469c529cd219380ea8da345, I added our [Use Case Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Use-Case-Diagram) and [Class Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram) deliverables.

* The files are uploaded in Markdown format. You can check files here, in the relevant branch:
    * [deliverables/CMPE451_Customer_Presentation_Milestone_1/UML_Use_Case_Diagram.md](https://github.com/bounswe/bounswe2022group7/commit/b349b699fc5a30dd1469c529cd219380ea8da345#diff-6eca2668939b9ac142f977511b40efaa54ba670a7fed433158c8f05b598edc1f) 
    * [deliverables/CMPE451_Customer_Presentation_Milestone_1/UML_Class_Diagram.md](https://github.com/bounswe/bounswe2022group7/commit/b349b699fc5a30dd1469c529cd219380ea8da345#diff-665cf21518e5cabaf73e1bceda9cc1f3ccd6d76afbf29f8e6d16bf0fdb822d7f)

**Comment by CahidArda** [comment]
Task was handled and the deliverables are added to our develop branch. Closing the issue.
