### ISSUE TITLE
Writing your own responsibilities for Part 6 and 7 of Milestone Group Review

### ISSUE THREAD

**Issue by ENESAYDOGDUOGLU** [bounswe/bounswe2022group7#373]
We should add our own responsibilities and tasks for Part 6 and Part 7 of Customer Milestone Group Review

6. Overall description of responsibilities that are assigned to each member.
7. A Summary of work performed by each team member (in tabular format).

Please click the buttons below when you have added your part.

- [ ] Ali Can Milani
- [ ] Atilla Türkmen
- [ ] Başak Önder
- [ ] Cahid Arda Öz
- [ ] Can Atakan Uğur
- [ ] Demet Yayla
- [x] Enes Aydoğduoğlu
- [ ] Erim Erkin Doğan
- [ ] Güney İzol
- [ ] Musa Şimşek
- [x] Sabri Mete Akyüz

**Comment by canatakan** [comment]
* Hello @ENESAYDOGDUOGLU, thank you for your intention of pinging everyone and reminding them their responsibility. 

* However, we had a discussion about this issue format before: The format of assigning everyone to an issue and having checkboxes with the names of them in the description is not a good issue format. Since this issue will always be waiting for everyone to complete their parts, it may remain open forever. Also, people will not feel so responsible when the entire team is assigned anyway. Therefore, this issue format is not a helpful tool to track tasks.

* The report is now completed anyway and all members in the list have filled their contributions. The report shall be added to our deliverables folder very soon, and thus, closing the issue.
