### ISSUE TITLE
[Frontend] Revise sign-up experience

### ISSUE THREAD

**Issue by erimerkin** [bounswe/bounswe2022group7#418]
In our Customer Presentation 1, few suggestions about our applications were made. One of these was revising the signup experience by seperating the optional fields from the sign-up and moving them to after registration. So I will modify our web application to achieve these suggestions.

In line with the requests api's signup endpoint was updated, but for seamless sign-up and login integration a update will be needed to API, automatically signing in the succesful signups.

**Tasks:**
- [x] Remove optional fields from registration (**commit:** [f9f6d13](https://github.com/bounswe/bounswe2022group7/commit/f9f6d1339eff1b36e0edcce0857a04e956af5fa2))
- [x] Implement new user detail component for entering optional items.
- [x] Update the endpoint connection 
- [x] Revise the registration process by automatically logging in the succesful tries and showing a "complete your profile" option. (waiting for #419)

**Deadline: 23.59 2022-11-21**
**Reviewer: @CahidArda**

**Comment by erimerkin** [comment]
To achieve the automatic logging in process a feature request was made to backend team in #419, so this issue will wait for the change to finalize.

**Comment by erimerkin** [comment]
I have finished the implementation of revised experience except for connection to API, which will be added after endpoint is created and merged.

# New User Experience

After a succesful sign-up user will automatically logged in and be redirected to a page to complete their profiles. The user have the option to skip this page without filling the details(redirected to home page), neither of the details are necessary for continuing. 

## New Sign-up Page

Optional fields of **name, surname, age** and **country** is deleted and moved to a new screen.

<img width="630" alt="resim" src="https://user-images.githubusercontent.com/26660856/203084832-352b059a-e558-4561-8a5c-fd8e31e100b1.png">

<img width="375" src="https://user-images.githubusercontent.com/26660856/203089431-ffe24459-2b6d-4cab-b91c-37ccb2af5e71.png" >


## Complete Profile Page

<img width="699" alt="resim" src="https://user-images.githubusercontent.com/26660856/203084114-597d1277-5086-4c85-9b61-e5bdd27c5121.png">

<img width="375" src="https://user-images.githubusercontent.com/26660856/203089634-b3c62416-23fa-42fa-a0e7-e76dfa0c663a.png">



#### Country Selector
<img width="699" alt="resim" src="https://user-images.githubusercontent.com/26660856/203084227-efe28bd5-4272-4008-8b8b-4933e078de09.png">


<img width="375" alt="resim" src="https://user-images.githubusercontent.com/26660856/203090008-40ad8edb-6e4a-4dd3-b284-fe88e47a1694.png">



#### Date Picker

Date Picker uses the native picker implemented in browsers so the below view could change depending on browser.

<img width="699" alt="resim" src="https://user-images.githubusercontent.com/26660856/203084164-4651cfe2-e0de-43f0-a8be-505a83d3457c.png">

<img width="375" alt="resim" src="https://user-images.githubusercontent.com/26660856/203090037-0950cd70-505b-4576-9c36-cb40cfc2aa6f.png">

----

# Additions

## Components

Four customizable and reusable components are created for future and current development.

### ImageUploader

This component will be used to handle selecting an image from local computer, converting it to base64 while showing preview of the image. It will take several props for customization:

-   **label:** This prop defines what will be written on the button
- **value:** This prop is necessary for storing the image address and showing the preview.
- **onChange:** This prop handles the value(should pass an hook setting state of value)
- **imgComponent:** This allows user to use another component for images. Optional.
- **width:** Sets width of the default image component. Optional.
- **height:** Sets height of the default image component. Optional.

#### Example Usage:

```JavaScript
<ImageUploader 
   label="Upload profile photo" 
   imgComponent={<Avatar sx={{ width: 96, height: 96 }} 
   src={selectedImage} alt="username" />} 
   value={selectedImage} 
   onChange={setSelectedImage} />
```

### CountrySelect

This component is used to select a country from a list of countries. 

#### Props:
- **label:** Defines the label of select input. Required
- **onChange:** This prop is used to set a state in parent component. Required.
- **width:** Optional prop, if not given it is set to 300px.

#### Example Usage:
```JavaScript
 <CountrySelect 
   name="country" 
   width="100%" 
   onChange={setSelectedCountry} />
```

### CustomOutlinedInput

This component is implemented for unsupported input types for MUI. Its type can be easily changed with `type` prop.

#### Example Usage:
```JavaScript
<CustomOutlinedInput 
placeholder="BirthDate" 
type="date" 
fullWidth 
name="dateOfBirth" 
label="Birth Date"
value={selecteddateOfBirth} 
onChange={setSelecteddateOfBirth} />
```

### EditUserInfo

This component is used to edit user's information. Current implementation doesn't fetch user's previous data and the changes cannot be sent to api since endpoint is not implemented for both situations.

-----

### GenericCardLayout

A generic layout card is created with overrideable maximum width. This layout component could replace the need for different types of layouts (Form, Content) with overriding the maximum width.

**Comment by erimerkin** [comment]
With commit 0671112 I have finished the implementation of revised signup experience. 

I have also added a new component named LoadingButton. It takes the below props:

- **loadingIcon:** An optional prop for passing a loading icon.
- **loadingText:** Text to be shown when loading.
- **loading:** Loading state
- **type:** Button type
-  **variant:** Button variant (contained, text, raised)
- **color:** Button color
- **size:** Button size(small, medium, etc.)
- **onClick:** Function to handle on click
- **disabled:** Disable state
- **label:** Default label of button when not loading
- **sx:** Style prop

#### Example Usage

```JavaScript
<LoadingButton 
  loading={isLoading} 
  type="submit" 
  size="large" 
  variant="text" 
  sx={{ ml: 2 }} 
  label={buttonLabel} 
  loadingText="saving" />
```

**Comment by erimerkin** [comment]
A pull request is opened for this issue on #452. After succesful merging this issue will now be completed.

**Comment by CahidArda** [comment]
Task was completed and PR was merged. Closing the issue.
