### ISSUE TITLE
Prepare Executive Summary For Group Milestone 2 Report

### ISSUE THREAD

**Issue by ENESAYDOGDUOGLU** [bounswe/bounswe2022group7#509]
Executive summary:

- [ ] Provide a summary of project status
- [ ] Describe any changes our team has made or planned since Milestone 1 to improve development process, explain how those changes will impact our process
- [ ] Describe the improvements we have planned for the remainder of your project

One person from the frontend and one person mobile team may help on this task.

**Comment by canatakan** [comment]
I totally missed this issue, sorry for the late review. This part is okay and it summarizes our current situation in the project. Thank you for your contribution, closing the issue.
